<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>HalconWorkflow.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Nodify" Version="7.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\HalconWorkflow.Core.csproj" />
    <ProjectReference Include="..\Abstractions\HalconWorkflow.Abstractions.csproj" />
    <ProjectReference Include="..\Runtime\HalconWorkflow.Runtime.csproj" />
    <ProjectReference Include="..\Nodes.Flow\HalconWorkflow.Nodes.Flow.csproj" />
    <ProjectReference Include="..\Nodes.Vision\HalconWorkflow.Nodes.Vision.csproj" />
  </ItemGroup>

</Project>
